server:
  port: 7900
#单节点
#应用名称及验证账号
spring:
  application: 
    name: eureka
  security: 
    user: 
      name: root
      password: root
eureka:
  client:
    register-with-eureka: true # 是否注册到eureka
    fetch-registry: false      # 是否需要拉取服务信息，默认未true
    service-url:               # Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://root:root@localhost:7900/eureka/ #这里的root是security的用户和密码，自已注册也要认证
      #defaultZone: http://root:root@eureka-7900:7900/eureka/ #需要在hosts里配置：127.0.0.1 eureka-7900
  server: 
    #关闭自我保护
    enable-self-preservation: false
    #清理间隔时间
    eviction-interval-timer-in-ms: 5000
logging:
  level:
    root: info