server:
  port: 7900
#单节点
#应用名称及验证账号
spring:
  application: 
    name: eureka
  security: 
    user: 
      name: root
      password: root
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://root:root@localhost:7900/eureka/,http://root:root@localhost:7901/eureka/,http://root:root@localhost:7902/eureka/ #这里的root是security的用户和密码，自已注册也要认证
  server: 
    #关闭自我保护
    enable-self-preservation: false
    #清理间隔时间
    eviction-interval-timer-in-ms: 5000
logging:
  level:
    root: info